defaults: &defaults
  working_directory: ~/circleci-base-image
  docker:
    - image: docker:18.06.1-ce-git

version: 2
jobs:
  compile:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
          name: docker push
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apk --no-cache add bash
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
              bash ./build.sh              
            fi

workflows:
  version: 2
  main:
    jobs:
      - compile:
          context: docker-login
          filters:
            tags: # all tags
              only: /.*/          